artifacts_root: artifacts

data_root: data

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/updated_base_model.h5

preprocess_data:
  preprocessed_data_dir: artifacts/preprocessed_data
  image_tensors_path: artifacts/preprocessed_data/tensors.pkl
  labels_path: artifacts/preprocessed_data/labels.pkl

training:
  trained_model_dir: artifacts/trained_model
  trained_model_path: artifacts/trained_model/trained_model.keras

prediction:
  prediction_dir: predict
  trained_model_path: artifacts/trained_model/trained_model.keras